# Generated by Django 3.1.1 on 2020-10-11 16:04

from django.db import migrations, models
import django.db.models.deletion
import mashgame.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MASHData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_1', models.CharField(default='Home', max_length=100)),
                ('home_2', models.CharField(default=None, max_length=100)),
                ('spouse_1', models.CharField(default='Nina', max_length=100)),
                ('spouse_2', models.CharField(default=None, max_length=100)),
                ('numchild_1', models.CharField(default='2', max_length=100)),
                ('numchild_2', models.CharField(default=None, max_length=100)),
                ('luxury_1', models.CharField(default='A Cup Of Coffee', max_length=100)),
                ('luxury_2', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('secret', 'secret')], default='secret', max_length=7)),
                ('authorized', models.BooleanField(default=False)),
                ('visit_count', models.IntegerField(default=0)),
                ('lucky_number', models.IntegerField(default=3, validators=[mashgame.models.validate_1_to_10])),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashgame.user')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mash_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mashgame.mashdata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mashgame.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_attacks', to='mashgame.user')),
                ('mash_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mashgame.mashdata')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_attacks', to='mashgame.user')),
            ],
        ),
    ]
