# Generated by Django 3.1.1 on 2020-10-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mashgame', '0002_auto_20201012_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Home', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Luxury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Luxury', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NumChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Number of Childs', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Spouse Name', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='home_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mashgame.home'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='home_2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mashgame.home'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='luxury_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mashgame.luxury'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='luxury_2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mashgame.luxury'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='numchild_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mashgame.numchild'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='numchild_2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mashgame.numchild'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='spouse_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mashgame.spouse'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='spouse_2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mashgame.spouse'),
        ),
    ]
