# Generated by Django 3.1.1 on 2020-10-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mashgame', '0003_auto_20201015_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashgame.user')),
            ],
        ),
    ]
