# Generated by Django 3.1.1 on 2020-10-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mashgame', '0004_authorizedhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedhash',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashes', to='mashgame.user'),
        ),
        migrations.AlterField(
            model_name='authorizedhash',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='home_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.home'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='home_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.home'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='luxury_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.luxury'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='luxury_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.luxury'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='numchild_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.numchild'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='numchild_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.numchild'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='spouse_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.spouse'),
        ),
        migrations.AlterField(
            model_name='mashdata',
            name='spouse_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.spouse'),
        ),
    ]
