# Generated by Django 3.1.1 on 2020-10-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mashgame', '0006_remove_user_authorized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='mash_data',
        ),
        migrations.AddField(
            model_name='attack',
            name='attack_data',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack_data', to='mashgame.mashdata'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('secret', 'Secret')], default='secret', max_length=7),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mashgame.user'),
        ),
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mash_value', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('attacker_points', models.IntegerField(default=0)),
                ('reciever_points', models.IntegerField(default=0)),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.home')),
                ('luxury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.luxury')),
                ('numchild', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.numchild')),
                ('spouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mashgame.spouse')),
            ],
        ),
        migrations.AddField(
            model_name='attack',
            name='result_data',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_data', to='mashgame.resultdata'),
        ),
    ]
