# Generated by Django 3.1.1 on 2020-11-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mashgame', '0007_auto_20201018_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='result_data',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_data', to='mashgame.resultdata'),
        ),
    ]
