# Generated by Django 3.1.1 on 2020-11-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mashgame', '0008_auto_20201109_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='result_data',
        ),
        migrations.AddField(
            model_name='resultdata',
            name='attack',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack', to='mashgame.attack'),
        ),
    ]
