# Generated by Django 3.1.1 on 2020-11-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mashgame', '0009_auto_20201109_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdata',
            name='attack',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_data', to='mashgame.attack'),
        ),
    ]
